#ifndef HAM_MIME_TYPES_H
#define HAM_MIME_TYPES_H 1

/**
 * @defgroup HAM_MIME Common MIME types
 * @ingroup HAM
 * @{
 */

#define HAM_MIME_AAC "audio/aac"
#define HAM_MIME_ABW "application/x-abiword"
#define HAM_MIME_ARC "application/x-freearc"
#define HAM_MIME_AVIF "image/avif"
#define HAM_MIME_AVI "video/x-msvideo"
#define HAM_MIME_AZW "application/vnd.amazon.ebook"
#define HAM_MIME_BIN "application/octet-stream"
#define HAM_MIME_BMP "image/bmp"
#define HAM_MIME_BZ "application/x-bzip"
#define HAM_MIME_BZ2 "application/x-bzip2"
#define HAM_MIME_CDA "application/x-cdf"
#define HAM_MIME_CSH "application/x-csh"
#define HAM_MIME_CSS "text/css"
#define HAM_MIME_CSV "text/csv"
#define HAM_MIME_DLL "application/x-dosexec"
#define HAM_MIME_DOC "application/msword"
#define HAM_MIME_DOCX "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
#define HAM_MIME_ELF "application/x-elf"
#define HAM_MIME_EOT "application/vnd.ms-fontobject"
#define HAM_MIME_EPUB "application/epub+zip"
#define HAM_MIME_EXE "application/x-msdownload"
#define HAM_MIME_GZ "application/gzip"
#define HAM_MIME_GIF "image/gif"
#define HAM_MIME_HTML "text/html"
#define HAM_MIME_ICO "image/vnd.microsoft.icon"
#define HAM_MIME_ICS "text/calendar"
#define HAM_MIME_JAR "application/java-archive"
#define HAM_MIME_JPEG "image/jpeg"
#define HAM_MIME_JS "text/javascript"
#define HAM_MIME_JSON "application/json"
#define HAM_MIME_JSONLD "application/ld+json"
#define HAM_MIME_MID "audio/x-midi"
#define HAM_MIME_MJS "text/javascript"
#define HAM_MIME_MP3 "audio/mpeg"
#define HAM_MIME_MP4 "video/mp4"
#define HAM_MIME_MPEG "video/mpeg"
#define HAM_MIME_MPKG "application/vnd.apple.installer+xml"
#define HAM_MIME_ODP "application/vnd.oasis.opendocument.presentation"
#define HAM_MIME_ODS "application/vnd.oasis.opendocument.spreadsheet"
#define HAM_MIME_ODT "application/vnd.oasis.opendocument.text"
#define HAM_MIME_OGA "audio/ogg"
#define HAM_MIME_OGV "video/ogg"
#define HAM_MIME_OGX "application/ogg"
#define HAM_MIME_OPUS "audio/opus"
#define HAM_MIME_OTF "font/otf"
#define HAM_MIME_PNG "image/png"
#define HAM_MIME_PDF "application/pdf"
#define HAM_MIME_PHP "application/x-httpd-php"
#define HAM_MIME_PPT "application/vnd.ms-powerpoint"
#define HAM_MIME_PPTX "application/vnd.openxmlformats-officedocument.presentationml.presentation"
#define HAM_MIME_RAR "application/vnd.rar"
#define HAM_MIME_RTF "application/rtf"
#define HAM_MIME_SH "application/x-sh"
#define HAM_MIME_SO "application/x-sharedlib"
#define HAM_MIME_SVG "image/svg+xml"
#define HAM_MIME_SWF "application/x-shockwave-flash"
#define HAM_MIME_TAR "application/x-tar"
#define HAM_MIME_TIFF "image/tiff"
#define HAM_MIME_TS "video/mp2t"
#define HAM_MIME_TTF "font/ttf"
#define HAM_MIME_TXT "text/plain"
#define HAM_MIME_VSD "application/vnd.visio"
#define HAM_MIME_WAV "audio/wav"
#define HAM_MIME_WEBA "audio/webm"
#define HAM_MIME_WEBM "video/webm"
#define HAM_MIME_WEBP "image/webp"
#define HAM_MIME_WOFF "font/woff"
#define HAM_MIME_WOFF2 "font/woff2"
#define HAM_MIME_XHTML "application/xhtml+xml"
#define HAM_MIME_XLS "application/vnd.ms-excel"
#define HAM_MIME_XLSX "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
#define HAM_MIME_XML "application/xml"
#define HAM_MIME_XUL "application/vnd.mozilla.xul+xml"
#define HAM_MIME_ZIP "application/zip"
#define HAM_MIME_3GP "video/3gpp"
#define HAM_MIME_3G2 "video/3gpp2"
#define HAM_MIME_7Z "application/x-7z-compressed"

/**
 * @}
 */

#endif // !HAM_MIME_TYPES_H

